# PostgreSQL. Versions 9.1 and up are supported.
# SQLite version 3.x

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# Use postgress for Heroku
production:
  database: postgresql-corrugated-37353
  adapter: postgresql
  host: localhost
  password:
  encoding: utf8
  pool: 15
